name: Build our Code and Test it (Pytest)

on:
  push:
    branches: ["main"]

jobs:
  # name of the job
  Setting-Up-Env-And-Running-Test:
    env:
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}
      DB_NAME: ${{secrets.DB_NAME}}

    runs-on: ubuntu-latest
    steps:
      - name: Pulling our git repo from main branch
        uses: actions/checkout@v6

      - name: Installing Python 3.13.5
        uses: actions/setup-python@v6
        with:
          python-version: '3.13.5' 

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      - name: Installing all Dependencies from requirements.txt
        run: pip install -r requirements.txt

      - name: Installing Pytest
        run: pip install pytest

      - name: Running Pytest
        run: pytest

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          context: ./
          file: ./Dockerfile
          tags: ${{secrets.DOCKERHUB_USERNAME}}/fastapi-first-one:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

