name: Build our Code ( as of now )

on:
  push:
    branches: ["main"]

jobs:
  # name of the job
  Setting-Up-Env:
    runs-on: ubuntu-latest
    steps:
      - name: Pulling our git repo from main branch
        uses: actions/checkout@v6

      - name: Installing Python 3.13.5
        uses: actions/setup-python@v6
        with:
          python-version: '3.13.5' 

      - name: Upgrade Pip
        run: python -m pip install --upgrade pip

      - name: Installing all Dependencies from requirements.txt
        run: pip install -r requirements.txt

      - name: Installing Pytest
        run: pip install pytest

      - name: Running Pytest 
        run: pytest

      


